CREATE TABLE IF NOT EXISTS STUDENT(
ROLL_No TEXT PRIMARY KEY,
NAME TEXT NOT NULL,
ADDRESS TEXT,
PHONE TEXT,
AGE Integer
);

INSERT INTO STUDENT (ROLL_NO,NAME,ADDRESS,PHONE,AGE) VALUES
('1', 'RAM', 'DELHI', '*******', '20'), 
('2', 'SHIVAM', 'ROHTAK', '*******', '15'), 
('3', 'SHREYANSH', 'DELHI', '*******', '18');

SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS='DELHI';

SELECT * FROM STUDENT WHERE AGE = 18 AND NAME='RAM';

SELECT * FROM STUDENT WHERE NAME = 'RAM' OR NAME='SHREYANSH';

SELECT * FROM STUDENT WHERE NAME = 'RAM' OR AGE=20;

SELECT * FROM STUDENT WHERE AGE=18 AND (NAME='SHREYANSH'OR NAME='RAM');